wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1711471394.54979
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.5
      8:
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 50
img_scale:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
save_checkpoint:
  desc: null
  value: true
